// project images
export const images = [
    {
      id: 1,
      name: "Team Profile Generator",
      alt: "Team Profile screenshot",
      src: "../../../../../assets/projects/0.png",
      deployUrl: "https://shaquilleoriol.github.io/TeamProfileGenerator/",
      deployLabel: "Visit Website",
      githubUrl: "https://github.com/ShaquilleOriol/TeamProfileGenerator",
      githubLabel: "Go to GitHub Repository",
    },
    {
      id: 2,
      name: "Read ME",
      alt: "ReadME screenshot",
      src: "../../../../../assets/projects/5.png",
      deployUrl: "https://shaquilleoriol.github.io/ReadMeGenerator/",
      deployLabel: "Visit Website",
      githubUrl: "https://github.com/ShaquilleOriol/ReadMeGenerator",
      githubLabel: "Go to GitHub Repository",
    },
    {
      id: 3,
      name: "Weather App",
      alt: "Weather screenshot",
      src: "../../../../../assets/projects/7.png",
      deployUrl: "https://shaquilleoriol.github.io/Weather-dash/",
      deployLabel: "Visit Website",
      githubUrl: "https://github.com/ShaquilleOriol/Weather-dash",
      githubLabel: "Go to GitHub Repository",
    },
    {
      id: 4,
      name: "Code Quiz",
      alt: "Code Quiz screenshot",
      src: "../../../../../assets/projects/4.png",
      deployUrl: "https://shaquilleoriol.github.io/codeQuiz/",
      deployLabel: "Visit Website",
      githubUrl: "https://github.com/ShaquilleOriol/codeQuiz",
      githubLabel: "Go to GitHub Repository",
    },
    {
      id: 5,
      name: "Din Din!",
      alt: "DinDin screenshot",
      src: "../../../../../assets/projects/2.png",
      deployUrl: "https://manorathn.github.io/group_5_project_1/",
      deployLabel: "Visit Website",
      githubUrl: "https://github.com/ShaquilleOriol/group_5_project_1",
      githubLabel: "Go to GitHub Repository",
    },
    {
      id: 6,
      name: "Frienemies",
      alt: "Frienemies Screenshot",
      src: "../../../../../assets/projects/3.png",
      deployUrl: "https://damp-thicket-88352.herokuapp.com/login",
      deployLabel: "Visit Website",
      githubUrl: "https://github.com/ShaquilleOriol/project-2-group-3",
      githubLabel: "Go to GitHub Repository",
    },
    {
      id: 7,
      name: "Bootstrap",
      alt: "bootstrap screenshot",
      src: "../../../../../assets/projects/3.png",
      deployUrl: "https://shaquilleoriol.github.io/bootstrapResponsive/",
      deployLabel: "Visit Website",
      githubUrl: "https://github.com/ShaquilleOriol/bootstrapResponsive",
      githubLabel: "Go to GitHub Repository",
    },
  ];